/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by D:\GoPath\bin\informer-gen.exe. DO NOT EDIT.

package v2

import (
	"context"
	time "time"

	extensionsexamplecomv2 "github.com/gaoxinge/website-v2-operator/pkg/apis/extensions.example.com/v2"
	versioned "github.com/gaoxinge/website-v2-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/gaoxinge/website-v2-operator/pkg/client/informers/externalversions/internalinterfaces"
	v2 "github.com/gaoxinge/website-v2-operator/pkg/client/listers/extensions.example.com/v2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// WebsiteInformer provides access to a shared informer and lister for
// Websites.
type WebsiteInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v2.WebsiteLister
}

type websiteInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewWebsiteInformer constructs a new informer for Website type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewWebsiteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredWebsiteInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredWebsiteInformer constructs a new informer for Website type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredWebsiteInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExtensionsV2().Websites(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExtensionsV2().Websites(namespace).Watch(context.TODO(), options)
			},
		},
		&extensionsexamplecomv2.Website{},
		resyncPeriod,
		indexers,
	)
}

func (f *websiteInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredWebsiteInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *websiteInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&extensionsexamplecomv2.Website{}, f.defaultInformer)
}

func (f *websiteInformer) Lister() v2.WebsiteLister {
	return v2.NewWebsiteLister(f.Informer().GetIndexer())
}
