/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by D:\GoPath\bin\client-gen.exe. DO NOT EDIT.

package v2

import (
	"context"
	"time"

	v2 "github.com/gaoxinge/website-v2-operator/pkg/apis/extensions.example.com/v2"
	scheme "github.com/gaoxinge/website-v2-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WebsitesGetter has a method to return a WebsiteInterface.
// A group's client should implement this interface.
type WebsitesGetter interface {
	Websites(namespace string) WebsiteInterface
}

// WebsiteInterface has methods to work with Website resources.
type WebsiteInterface interface {
	Create(ctx context.Context, website *v2.Website, opts v1.CreateOptions) (*v2.Website, error)
	Update(ctx context.Context, website *v2.Website, opts v1.UpdateOptions) (*v2.Website, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2.Website, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2.WebsiteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.Website, err error)
	WebsiteExpansion
}

// websites implements WebsiteInterface
type websites struct {
	client rest.Interface
	ns     string
}

// newWebsites returns a Websites
func newWebsites(c *ExtensionsV2Client, namespace string) *websites {
	return &websites{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the website, and returns the corresponding website object, and an error if there is any.
func (c *websites) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2.Website, err error) {
	result = &v2.Website{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("websites").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Websites that match those selectors.
func (c *websites) List(ctx context.Context, opts v1.ListOptions) (result *v2.WebsiteList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2.WebsiteList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("websites").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested websites.
func (c *websites) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("websites").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a website and creates it. Returns the server's representation of the website, and an error, if there is any.
func (c *websites) Create(ctx context.Context, website *v2.Website, opts v1.CreateOptions) (result *v2.Website, err error) {
	result = &v2.Website{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("websites").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(website).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a website and updates it. Returns the server's representation of the website, and an error, if there is any.
func (c *websites) Update(ctx context.Context, website *v2.Website, opts v1.UpdateOptions) (result *v2.Website, err error) {
	result = &v2.Website{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("websites").
		Name(website.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(website).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the website and deletes it. Returns an error if one occurs.
func (c *websites) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("websites").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *websites) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("websites").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched website.
func (c *websites) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.Website, err error) {
	result = &v2.Website{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("websites").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
